baseURL = "https://neovasudeva.github.io/"
languageCode = "en-us"
title = "Neo's Site"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true # show reading time
  Toc = true # table of contents

[languages]
  [languages.en]
    title = "Neo's Site"
    subtitle = "Personal site"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Neo's Site"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/neovasudeva"
        weight = 3

