name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build 
        run: |
          sudo apt-get install pandoc
          pip install pypandoc
          python md2html.py

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages 
          folder: build 